language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
    allow_failures:
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - composer install -n
    - php public/index.php orm:schema-tool:create
    - cp files/db/dev.sqlite files/db/testing.sqlite

notifications:
  email: false
